#ifndef __SCHEMA__
#define __SCHEMA__

#ifdef __cplusplus
namespace swss {
#endif

/***** DATABASE *****/

#define APPL_DB         0
#define ASIC_DB         1
#define COUNTERS_DB     2
#define LOGLEVEL_DB     3
#define CONFIG_DB       4
#define PFC_WD_DB       5
#define FLEX_COUNTER_DB 5
#define STATE_DB        6
#define SNMP_OVERLAY_DB 7
#define RESTAPI_DB      8
#define GB_ASIC_DB      9
#define HISTORY_DB      10
#define GB_FLEX_COUNTER_DB  11
#define CHASSIS_APP_DB      12
#define CHASSIS_STATE_DB    13

/***** APPLICATION DATABASE *****/

#define APP_LINECARD_TABLE_NAME           "APP_LINECARD"
#define APP_PORT_TABLE_NAME               "APP_PORT"
#define APP_TRANSCEIVER_TABLE_NAME        "APP_TRANSCEIVER"
#define APP_LOGICALCHANNEL_TABLE_NAME     "APP_LOGICAL_CHANNEL"
#define APP_OTN_TABLE_NAME                "APP_OTN"
#define APP_ETHERNET_TABLE_NAME           "APP_ETHERNET"
#define APP_PHYSICALCHANNEL_TABLE_NAME    "APP_PHYSICAL_CHANNEL"
#define APP_ASSIGNMENT_TABLE_NAME         "APP_ASSIGNMENT"
#define APP_OCH_TABLE_NAME                "APP_OCH"
#define APP_LLDP_TABLE_NAME               "APP_LLDP"

#define APP_INTERFACE_TABLE_NAME              "APP_INTERFACE"
#define APP_OA_TABLE_NAME                     "APP_AMPLIFIER"
#define APP_OSC_TABLE_NAME                    "APP_OSC"
#define APP_APS_TABLE_NAME                    "APP_APS"
#define APP_APSPORT_TABLE_NAME                "APP_APS_PORT"
#define APP_ATTENUATOR_TABLE_NAME             "APP_ATTENUATOR"

#define APP_OCM_TABLE_NAME                    "APP_OCM"
#define APP_OTDR_TABLE_NAME                   "APP_OTDR"

/***** ASIC DATABASE *****/
#define ASIC_TEMPERATURE_INFO_TABLE_NAME    "ASIC_TEMPERATURE_INFO"

/***** COUNTER DATABASE *****/

#define COUNTERS_TABLE                      "COUNTERS"
#define COUNTERS_DEBUG_NAME_LINECARD_STAT_MAP "COUNTERS_DEBUG_NAME_LINECARD_STAT_MAP"

#define COUNTERS_LINECARD_NAME_MAP            "COUNTERS_LINECARD_NAME_MAP"
#define COUNTERS_PORT_NAME_MAP                "COUNTERS_PORT_NAME_MAP"
#define COUNTERS_TRANSCEIVER_NAME_MAP         "COUNTERS_TRANSCEIVER_NAME_MAP"
#define COUNTERS_LOGICALCHANNEL_NAME_MAP      "COUNTERS_LOGICALCHANNEL_NAME_MAP"
#define COUNTERS_OTN_NAME_MAP                 "COUNTERS_OTN_NAME_MAP"
#define COUNTERS_ETHERNET_NAME_MAP            "COUNTERS_ETHERNET_NAME_MAP"
#define COUNTERS_PHYSICALCHANNEL_NAME_MAP     "COUNTERS_TRANSCEIVER_NAME_MAP"
#define COUNTERS_OCH_NAME_MAP                 "COUNTERS_OCH_NAME_MAP"
#define COUNTERS_LLDP_NAME_MAP                "COUNTERS_LLDP_NAME_MAP"
#define COUNTERS_ASSIGNMENT_NAME_MAP          "COUNTERS_ASSIGNMENT_NAME_MAP"
#define COUNTERS_INTERFACE_NAME_MAP           "COUNTERS_INTERFACE_NAME_MAP"
#define COUNTERS_OA_NAME_MAP                  "COUNTERS_AMPLIFIER_NAME_MAP"
#define COUNTERS_OSC_NAME_MAP                 "COUNTERS_OSC_NAME_MAP"
#define COUNTERS_APS_NAME_MAP                 "COUNTERS_APS_NAME_MAP"
#define COUNTERS_APSPORT_NAME_MAP             "COUNTERS_APSPORT_NAME_MAP"
#define COUNTERS_ATTENUATOR_NAME_MAP          "COUNTERS_ATTENUATOR_NAME_MAP"
#define COUNTERS_OCM_NAME_MAP                 "COUNTERS_OCM_NAME_MAP"
#define COUNTERS_OTDR_NAME_MAP                "COUNTERS_OTDR_NAME_MAP"

#define COUNTERS_LINECARD_TABLE_NAME                      "LINECARD"
#define COUNTERS_PORT_TABLE_NAME                          "PORT"
#define COUNTERS_TRANSCEIVER_TABLE_NAME                   "TRANSCEIVER"
#define COUNTERS_LOGICALCHANNEL_TABLE_NAME                "LOGICAL_CHANNEL"
#define COUNTERS_OTN_TABLE_NAME                           "OTN"
#define COUNTERS_ETHERNET_TABLE_NAME                      "ETHERNET"
#define COUNTERS_PHYSICALCHANNEL_TABLE_NAME               "TRANSCEIVER"
#define COUNTERS_OCH_TABLE_NAME                           "OCH"
#define COUNTERS_LLDP_TABLE_NAME                          "LLDP"
#define COUNTERS_ASSIGNMENT_TABLE_NAME                    "ASSIGNMENT"
#define COUNTERS_INTERFACE_TABLE_NAME                     "INTERFACE"
#define COUNTERS_OA_TABLE_NAME                            "AMPLIFIER"
#define COUNTERS_OSC_TABLE_NAME                           "OSC"
#define COUNTERS_APS_TABLE_NAME                           "APS"
#define COUNTERS_APSPORT_TABLE_NAME                       "APS_PORT"
#define COUNTERS_ATTENUATOR_TABLE_NAME                    "ATTENUATOR"
#define COUNTERS_OCM_TABLE_NAME                           "OCM"
#define COUNTERS_OTDR_TABLE_NAME                          "OTDR"

/***** LOGLEVEL DATABASE *****/

#define DAEMON_TABLE_NAME "DAEMON_TABLE"
#define DAEMON_LOGLEVEL "LOGLEVEL"
#define DAEMON_LOGOUTPUT "LOGOUTPUT"

/***** FLEX COUNTER DATABASE *****/

#define FLEX_COUNTER_TABLE              "FLEX_COUNTER_TABLE"

#define TRANSCEIVER_COUNTER_ID_LIST         "TRANSCEIVER_COUNTER_ID_LIST"
#define TRANSCEIVER_GAUGE_ID_LIST           "TRANSCEIVER_GAUGE_ID_LIST"
#define TRANSCEIVER_STATUS_ID_LIST          "TRANSCEIVER_STATUS_ID_LIST"

#define PHYSICALCH_COUNTER_ID_LIST         "PHYSICALCH_COUNTER_ID_LIST"
#define PHYSICALCH_GAUGE_ID_LIST           "PHYSICALCH_GAUGE_ID_LIST"
#define PHYSICALCH_STATUS_ID_LIST          "PHYSICALCH_STATUS_ID_LIST"

#define ETHERNET_COUNTER_ID_LIST         "ETHERNET_COUNTER_ID_LIST"
#define ETHERNET_STATUS_ID_LIST 	 "ETHERNET_STATUS_ID_LIST"

#define OTN_COUNTER_ID_LIST         "OTN_COUNTER_ID_LIST"
#define OTN_GAUGE_ID_LIST           "OTN_GAUGE_ID_LIST"
#define OTN_STATUS_ID_LIST           "OTN_STATUS_ID_LIST"

#define LINECARD_STATUS_ID_LIST      "LINECARD_STATUS_ID_LIST"
#define LINECARD_COUNTER_ID_LIST     "LINECARD_COUNTER_ID_LIST"
#define LINECARD_GAUGE_ID_LIST       "LINECARD_GAUGE_ID_LIST"

#define OPTICALCH_STATUS_ID_LIST     "OPTICALCH_STATUS_ID_LIST"
#define OPTICALCH_GAUGE_ID_LIST      "OPTICALCH_GAUGE_ID_LIST"
#define OPTICALCH_COUNTER_ID_LIST    "OPTICALCH_COUNTER_ID_LIST"

#define PORT_STATUS_ID_LIST          "PORT_STATUS_ID_LIST"
#define PORT_GAUGE_ID_LIST           "PORT_GAUGE_ID_LIST"
#define INPORT_GAUGE_ID_LIST         "INPORT_GAUGE_ID_LIST"
#define OUTPORT_GAUGE_ID_LIST        "OUTPORT_GAUGE_ID_LIST"

#define LOGICALCH_COUNTER_ID_LIST     "LOGICALCH_COUNTER_ID_LIST"
#define LOGICALCH_STATUS_ID_LIST      "LOGICALCH_STATUS_ID_LIST"
#define LLDP_STATUS_ID_LIST           "LLDP_STATUS_ID_LIST"

#define ASSIGNMENT_STATUS_ID_LIST         "ASSIGNMENT_STATUS_ID_LIST"

#define INTERFACE_COUNTER_ID_LIST         "INTERFACE_COUNTER_ID_LIST"
#define INTERFACE_GAUGE_ID_LIST           "INTERFACE_GAUGE_ID_LIST"
#define INTERFACE_STATUS_ID_LIST          "INTERFACE_STATUS_ID_LIST"

#define OA_COUNTER_ID_LIST         "AMPLIFIER_COUNTER_ID_LIST"
#define OA_GAUGE_ID_LIST           "AMPLIFIER_GAUGE_ID_LIST"
#define OA_STATUS_ID_LIST          "AMPLIFIER_STATUS_ID_LIST"

#define OSC_COUNTER_ID_LIST         "OSC_COUNTER_ID_LIST"
#define OSC_GAUGE_ID_LIST           "OSC_GAUGE_ID_LIST"
#define OSC_STATUS_ID_LIST          "OSC_STATUS_ID_LIST"

#define APS_COUNTER_ID_LIST         "APS_COUNTER_ID_LIST"
#define APS_GAUGE_ID_LIST           "APS_GAUGE_ID_LIST"
#define APS_STATUS_ID_LIST          "APS_STATUS_ID_LIST"

#define APSPORT_COUNTER_ID_LIST         "APSPORT_COUNTER_ID_LIST"
#define APSPORT_GAUGE_ID_LIST           "APSPORT_GAUGE_ID_LIST"
#define APSPORT_STATUS_ID_LIST          "APSPORT_STATUS_ID_LIST"

#define ATTENUATOR_COUNTER_ID_LIST         "ATTENUATOR_COUNTER_ID_LIST"
#define ATTENUATOR_GAUGE_ID_LIST           "ATTENUATOR_GAUGE_ID_LIST"
#define ATTENUATOR_STATUS_ID_LIST          "ATTENUATOR_STATUS_ID_LIST"

#define OCM_STATUS_ID_LIST                 "OCM_STATUS_ID_LIST"
#define OTDR_STATUS_ID_LIST                "OTDR_STATUS_ID_LIST"

#define LINECARD_DEBUG_COUNTER_ID_LIST    "LINECARD_DEBUG_COUNTER_ID_LIST"
#define LINECARD_DEBUG_COUNTER_ID_LIST    "LINECARD_DEBUG_COUNTER_ID_LIST"
#define PLUGIN_TABLE                    "PLUGIN_TABLE"
#define LUA_PLUGIN_TYPE                 "LUA_PLUGIN_TYPE"

#define POLL_INTERVAL_FIELD           "POLL_INTERVAL"
#define STATS_MODE_FIELD              "STATS_MODE"
#define STATS_MODE_READ               "STATS_MODE_READ"
#define STATS_MODE_READ_AND_CLEAR     "STATS_MODE_READ_AND_CLEAR"

#define FLEX_COUNTER_STATUS_FIELD     "FLEX_COUNTER_STATUS"
#define FLEX_COUNTER_GROUP_TABLE      "FLEX_COUNTER_GROUP_TABLE"

/***** CONFIGURATION DATABASE *****/

#define CFG_INTF_TABLE_NAME               "INTERFACE"
#define CFG_LOOPBACK_INTERFACE_TABLE_NAME "LOOPBACK_INTERFACE"
#define CFG_MGMT_INTERFACE_TABLE_NAME     "MGMT_INTERFACE"
#define CFG_LAG_INTF_TABLE_NAME           "PORTCHANNEL_INTERFACE"
#define CFG_VLAN_INTF_TABLE_NAME          "VLAN_INTERFACE"
#define CFG_VLAN_SUB_INTF_TABLE_NAME      "VLAN_SUB_INTERFACE"

#define CFG_LINECARD_TABLE_NAME    "LINECARD"

#define CFG_BGP_NEIGHBOR_TABLE_NAME "BGP_NEIGHBOR"
#define CFG_BGP_INTERNAL_NEIGHBOR_TABLE_NAME "BGP_INTERNAL_NEIGHBOR"
#define CFG_BGP_MONITORS_TABLE_NAME "BGP_MONITORS"
#define CFG_BGP_PEER_RANGE_TABLE_NAME "BGP_PEER_RANGE"

#define CFG_DEVICE_METADATA_TABLE_NAME "DEVICE_METADATA"

#define CFG_DEVICE_NEIGHBOR_TABLE_NAME          "DEVICE_NEIGHBOR"
#define CFG_DEVICE_NEIGHBOR_METADATA_TABLE_NAME "DEVICE_NEIGHBOR_METADATA"

#define CFG_FLEX_COUNTER_TABLE_NAME "FLEX_COUNTER_TABLE"
#define CFG_FLEX_COUNTER_GROUP_TABLE_NAME "FLEX_COUNTER_GROUP_TABLE"
#define CFG_WATERMARK_TABLE_NAME "WATERMARK_TABLE"

#define CFG_WARM_RESTART_TABLE_NAME                 "WARM_RESTART"

#define CFG_DEBUG_COUNTER_TABLE_NAME                "DEBUG_COUNTER"
#define CFG_DEBUG_COUNTER_DROP_REASON_TABLE_NAME    "DEBUG_COUNTER_DROP_REASON"

#define CFG_FEATURE_TABLE_NAME                      "FEATURE"

#define CFG_LINECARD_TABLE_NAME                      "LINECARD"
#define CFG_PORT_TABLE_NAME                          "PORT"
#define CFG_TRANSCEIVER_TABLE_NAME                   "TRANSCEIVER"
#define CFG_LOGICALCHANNEL_TABLE_NAME                "LOGICAL_CHANNEL"
#define CFG_OTN_TABLE_NAME                           "OTN"
#define CFG_ETHERNET_TABLE_NAME                      "ETHERNET"
#define CFG_PHYSICALCHANNEL_TABLE_NAME               "PHYSICAL_CHANNEL"
#define CFG_ASSIGNMENT_TABLE_NAME                    "ASSIGNMENT"
#define CFG_OCH_TABLE_NAME                           "OCH"
#define CFG_LLDP_TABLE_NAME                          "LLDP"

#define CFG_INTERFACE_TABLE_NAME              "INTERFACE"
#define CFG_OA_TABLE_NAME                     "AMPLIFIER"
#define CFG_OSC_TABLE_NAME                    "OSC"
#define CFG_APS_TABLE_NAME                    "APS"
#define CFG_APSPORT_TABLE_NAME                "APS_PORT"
#define CFG_ATTENUATOR_TABLE_NAME             "ATTENUATOR"

#define CFG_OCM_GROUP_TABLE_NAME              "OCM_GROUP"
#define CFG_OCM_TABLE_NAME                    "OCM"

#define CFG_OTDR_GROUP_TABLE_NAME             "OTDR_GROUP"
#define CFG_OTDR_TABLE_NAME                   "OTDR"

/***** STATE DATABASE *****/
#define STATE_LINECARD_CAPABILITY_TABLE_NAME        "LINECARD_CAPABILITY_TABLE"
#define STATE_WARM_RESTART_TABLE_NAME               "WARM_RESTART_TABLE"
#define STATE_WARM_RESTART_ENABLE_TABLE_NAME        "WARM_RESTART_ENABLE_TABLE"

#define STATE_ASIC_TABLE                            "ASIC_TABLE"

#define STATE_PORT_TABLE_NAME                          "PORT"
#define STATE_TRANSCEIVER_TABLE_NAME                   "TRANSCEIVER"
#define STATE_LOGICALCHANNEL_TABLE_NAME                "LOGICAL_CHANNEL"
#define STATE_OTN_TABLE_NAME                           "OTN"
#define STATE_ETHERNET_TABLE_NAME                      "ETHERNET"
#define STATE_PHYSICALCHANNEL_TABLE_NAME               "PHYSICAL_CHANNEL"
#define STATE_ASSIGNMENT_TABLE_NAME                    "ASSIGNMENT"
#define STATE_OCH_TABLE_NAME                           "OCH"
#define STATE_LLDP_TABLE_NAME                          "LLDP"
#define STATE_LINECARD_TABLE_NAME                      "LINECARD"
#define STATE_REBOOT_TABLE_NAME                        "REBOOT"
#define STATE_CLEANPM_TABLE_NAME                       "CLEANPM"

#define STATE_INTERFACE_TABLE_NAME              "INTERFACE"
#define STATE_OA_TABLE_NAME                     "AMPLIFIER"
#define STATE_OSC_TABLE_NAME                    "OSC"
#define STATE_APS_TABLE_NAME                    "APS"
#define STATE_APSPORT_TABLE_NAME                "APS_PORT"
#define STATE_ATTENUATOR_TABLE_NAME             "ATTENUATOR"
#define STATE_OCM_TABLE_NAME                    "OCM"
#define STATE_OTDR_TABLE_NAME                   "OTDR"

/***** NOTIFICATION & REPLY *****/
#define LINECARD_NOTIFICATION            "LINECARD_NOTIFICATION"
#define PORT_NOTIFICATION                "PORT_NOTIFICATION"
#define TRANSCEIVER_NOTIFICATION         "TRANSCEIVER_NOTIFICATION"
#define LOGICALCHANNEL_NOTIFICATION      "LOGICALCHANNEL_NOTIFICATION"
#define OTN_NOTIFICATION                 "OTN_NOTIFICATION"
#define ETHERNET_NOTIFICATION            "ETHERNET_NOTIFICATION"
#define PHYSICALCHANNEL_NOTIFICATION     "TRANSCEIVER_NOTIFICATION"
#define OCH_NOTIFICATION                 "OCH_NOTIFICATION"
#define LLDP_NOTIFICATION                "LLDP_NOTIFICATION"
#define ASSIGNMENT_NOTIFICATION          "ASSIGNMENT_NOTIFICATION"
#define INTERFACE_NOTIFICATION           "INTERFACE_NOTIFICATION"
#define OA_NOTIFICATION                  "AMPLIFIER_NOTIFICATION"
#define OSC_NOTIFICATION                 "OSC_NOTIFICATION"
#define APS_NOTIFICATION                 "APS_NOTIFICATION"
#define APSPORT_NOTIFICATION             "APSPORT_NOTIFICATION"
#define ATTENUATOR_NOTIFICATION          "ATTENUATOR_NOTIFICATION"
#define OCM_NOTIFICATION                 "OCM_NOTIFICATION"
#define OTDR_NOTIFICATION                "OTDR_NOTIFICATION"
#define OTDR_GROUP_NOTIFICATION          "OTDR_GROUP_NOTIFICATION"

#define LINECARD_REPLY            "LINECARD_REPLY"
#define PORT_REPLY                "PORT_REPLY"
#define TRANSCEIVER_REPLY         "TRANSCEIVER_REPLY"
#define LOGICALCHANNEL_REPLY      "LOGICALCHANNEL_REPLY"
#define OTN_REPLY                 "OTN_REPLY"
#define ETHERNET_REPLY            "ETHERNET_REPLY"
#define PHYSICALCHANNEL_REPLY     "TRANSCEIVER_REPLY"
#define OCH_REPLY                 "OCH_REPLY"
#define LLDP_REPLY                "LLDP_REPLY"
#define ASSIGNMENT_REPLY          "ASSIGNMENT_REPLY"
#define INTERFACE_REPLY           "INTERFACE_REPLY"
#define OA_REPLY                  "AMPLIFIER_REPLY"
#define OSC_REPLY                 "OSC_REPLY"
#define APS_REPLY                 "APS_REPLY"
#define APSPORT_REPLY             "APSPORT_REPLY"
#define ATTENUATOR_REPLY          "ATTENUATOR_REPLY"
#define OCM_REPLY                 "OCM_REPLY"
#define OTDR_REPLY                "OTDR_REPLY"
#define OTDR_GROUP_REPLY          "OTDR_GROUP_REPLY"

/***** MISC *****/

#define SET_COMMAND "SET"
#define DEL_COMMAND "DEL"
#define EMPTY_PREFIX ""

#ifdef __cplusplus
}
#endif

#endif
